---
title: Hanzisize
author: rjpeterson
email: hanzisizeextension@gmail.com
description: Hanzisize is a browser extension that allows selective resizing of text
  according to the language selected by the user.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
